name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate script.js with API key
      - name: Generate script.js with API key
        run: |
          echo "const apiKey = '${{ secrets.YOUTUBE_API_KEY }}';" > script.js
          cat template.js >> script.js

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./          # Adjust if your site is in a subfolder
          publish_branch: gh-pages # Deploy to gh-pages branch
